databases:
 source:
  sourcedb1:
    host: 172.16.98.7
    port: 65432
    user: pg16_test
    password: test
    dbname: postgres
    dbtype: postgresql
 target:
  host: 172.16.98.7
  port: 65432
  user: pg16_test
  password: test
  dbname: postgres
  dbtype: postgresql
xms: 512m
xmx: 512m  
